### PR TITLE
Update SimpleCommandMap.php

### PR DESCRIPTION
**Pull request by HiggsInc**
Minor correction to TransferServerCommand which was originally in lowercase.

### CODE REVIEW

**Comment by inxomnyaa** [comment]
Oh lol, that mess again xd

Is it like this on pmmp?

**Comment by HiggsInc** [comment]
Yea lol. This correction is in line with pmmp

**Comment by inxomnyaa** [comment]
Fix the command class please
https://github.com/ClearSkyTeam/PocketMine-MP/blob/cs-1.0/src/pocketmine/command/defaults/TransferserverCommand.php#L30
and the file name

**Comment by HiggsInc** [comment]
Thanks will do

**Pull request merged**
