### PR TITLE
Master

### PR DESCRIPTION
**Pull request by glemsom**
## Introduction
Fix typecasting errors on 32bit

### CODE REVIEW

**Comment by inxomnyaa** [comment]
seeing no issue here. need to blame dkt i guess

merge when all fixes done, and Travis check succeeded

**Comment by inxomnyaa** [comment]
"pushing to the master branch"

Readme:

Only use cs-1.0

**Comment by glemsom** [comment]
Seems this has fixed issue #83

**Comment by inxomnyaa** [comment]
So what now

**Pull request merged**
