### PR TITLE
MASTER

### PR DESCRIPTION
**Pull request by junkdude**
Lots of fixes probably needed to be done.

### CODE REVIEW

**Comment by inxomnyaa** [comment]
@junkdude master is not even used 😂

**Comment by junkdude** [comment]
@thebigsmileXD so the master branch of pmmp isnt used?

**Comment by inxomnyaa** [comment]
@junkdude isn't this what i just said? Also, please read the readme, it should say pretty big that only cs-1.0 is modified

**Comment by junkdude** [comment]
the master branch IS USED and this is being merged into the cs-10 branch @thebigsmileXD

**Comment by inxomnyaa** [comment]
@junkdude nope

**Comment by inxomnyaa** [comment]
@thebigsmileXD i mean
.. i should know best as owner and only coder, right?!

**Pull request closed without merging**
