### PR TITLE
maybe work now

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by inxomnyaa** [comment]
Nope

**Comment by ghost** [comment]
@thebigsmileXD uhm it gives  a eror on your patch

[CRITICAL] Unable to find the PocketMine-SPL library.

**Comment by inxomnyaa** [comment]
I patched that into my edit, thx

**Comment by ghost** [comment]
your welcome @thebigsmileXD

**Comment by inxomnyaa** [comment]
There we go, it works!

**Pull request closed without merging**
