### PR TITLE
sick

### PR DESCRIPTION
**Pull request by JunkDaCoder**

### CODE REVIEW

**Comment by inxomnyaa** [comment]
Genisys, files via UPLOAD (like... wtf)

**Comment by inxomnyaa** [comment]
@thebigsmileXD ye wtf

**Comment by JunkDaCoder** [comment]
rip..i was trying to upload this to my branch of clearsky so i could merge prs from pmmp and clearsky but have some features

**Comment by inxomnyaa** [comment]
@JunkDaCoder Dude cs and pm have the same code

**Pull request closed without merging**
