### PR TITLE
Ignore Slots That Have Air

### PR DESCRIPTION
**Pull request by junkdude**
## Introduction

This fixes drag and dropping items to the hotbar on windows 10. 

### API changes

None
### Behavioural changes

none sited
## Backwards compatibility

Not sure

### CODE REVIEW

**Comment by inxomnyaa** [comment]
> Behavioural changes
None

Uhm..

Also.. What is the thing it tries to fix? Shift-clicking works for me

**Comment by junkdude** [comment]
@thebigsmileXD i forgot to change it to drag and dropping from the hotbar

**Comment by inxomnyaa** [comment]
Could you make a clip or so of the error before after?

**Comment by junkdude** [comment]
Unhandled item equiped

**Pull request merged**
